//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTRALAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXTRALAR()
        {
            this.MUSTERIEXTRALAR = new HashSet<MUSTERIEXTRALAR>();
        }
    
        public int EXTRAID { get; set; }
        public string AD { get; set; }
        public string FIYATTIPI { get; set; }
        public Nullable<int> FIYAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUSTERIEXTRALAR> MUSTERIEXTRALAR { get; set; }
    }
}
