//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSTERIRESIMLER
    {
        public int MUSTERIRESID { get; set; }
        public Nullable<int> MUSTERIID { get; set; }
        public Nullable<int> RESIMIDLER { get; set; }
    
        public virtual MUSTERILER MUSTERILER { get; set; }
        public virtual RESIMLER RESIMLER { get; set; }
    }
}
